---
title: "Teaching Codealongs in Zoom"
author: "C. M. Curry"
format: html
---

## Know your tools (carpentries)

Understand Zoom and [practice ahead of time](https://carpentries.github.io/instructor-training-bonus-modules/01-online-workshops-module-1.html)

## Screen and curriculum organizing
- Second monitor, hypothes.is annotations
- Tablet (talk to LTP if you are in library?, check out from desk if not)
- Paper versions (make sure your copy is up to date)

## Communicating with the learners
- Etherpad
- Zoom chat
- Zoom polls
- Hand raise

## You can't rely on watching everyone's faces

- Ask defined questions that can be answered in chat or with raised hands (yes or no)
  - Not great
    - "Did you understand?"
    - "How's it working?"
  - Better
    - "Paste code to answer this challenge" (chat)
    - "Raise your hand when you've completed the highlighted code" (sticky analogs)
    - "Paste your error and code into the chat if it doesn't work for you"
- Ask more often than in person, because it's harder to catch people up individually

## Avoid breakout rooms unless you're having a discussion

- Ensure you have at least one helper who can troubleshoot via chat
- Ask permission before having someone with difficulties share their screen
- Walk them through it slowly, do not take over
- Thank them for helping and re-iterate how everyone has similar problems in every workshop

## Practice changing host

- Make a poll
- Lower hands
- Assign people to breakout room
- See who's messaging you private vs everyone


## Raise hands
- Describe raising hands
- Stays visible to instructor, unlike "reactions" emojis

## Summary

- Have a separate screen
- Much more frequent check-ins, use hand raise
- Have a helper if you have more than half a dozen people

## More resources

[covid resources](https://docs.carpentries.org/resources/workshops/resources_for_online_workshops.html)
[online tips](https://carpentries.org/blog/2022/03/online-teaching-kcl/)
[community tips for online](https://carpentries.org/blog/2020/03/tips-for-teaching-online/)
[harvard zoom tutorial](https://teachremotely.harvard.edu/zoom-video-tutorials)
[zoom pedagogy](https://www.cmu.edu/canvas/teachingonline/zoom/zoompedagogy.html)
[how to teach tech together online notes](https://teachtogether.tech/en/index.html#s:finale) and [detailed online](https://teachtogether.tech/en/index.html#s:online)